# Generated by Django 4.2.15 on 2024-08-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=50)),
                ('dish_price', models.IntegerField(max_length=5)),
                ('cuisine', models.IntegerField(max_length=25)),
            ],
        ),
    ]
