# Generated by Django 4.2.15 on 2024-08-28 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_author_comment_post_tagline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(editable=False, max_length=1000)),
                ('card_title', models.CharField(max_length=50)),
                ('card_description', models.CharField(max_length=1000)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ImgAppDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/')),
                ('card_title', models.CharField(max_length=50)),
                ('card_description', models.CharField(max_length=1000)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='SimpleFormEntry',
        ),
        migrations.AlterField(
            model_name='author',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='imgappdb',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.author'),
        ),
        migrations.AddField(
            model_name='imgappdb',
            name='tags',
            field=models.ManyToManyField(null=True, to='portfolio.tagline'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.imgappdb'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
