# Generated by Django 4.2.15 on 2024-08-30 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_imgapp_imgappdb_remove_post_author_remove_post_tags_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImgApp',
        ),
    ]
