# Generated by Django 4.2.15 on 2024-08-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_author_city_author_rating_alter_author_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='', editable=False, null=True),
        ),
    ]
